CREATE TYPE user_role AS ENUM ('EMPLOYEE', 'SUPERVISOR', 'ADMINISTRATOR');
CREATE TYPE competency_type AS ENUM ('TRAINING', 'LICENSE', 'CERTIFICATION', 'SKILL', 'OTHER');

CREATE TABLE unit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    system_role user_role NOT NULL,
    CONSTRAINT uq_app_user_email UNIQUE (email)
);

CREATE TABLE employee_unit (
    employee_id BIGINT NOT NULL,
    unit_id BIGINT NOT NULL,
    CONSTRAINT pk_employee_unit PRIMARY KEY (employee_id, unit_id),
    -- The format "CONSTRAINT <constraint_name> FOREIGN KEY <column_name> REFERENCES <table_name> <column_name>"
    -- is used for clarity. The constraint is optional, but it can be useful in error messages and for database changes.
    -- This is identical to "employee_id BIGINT NOT NULL REFERENCES app_user (id)".
    CONSTRAINT fk_employee_unit_employee
        FOREIGN KEY (employee_id) REFERENCES app_user (id),
    CONSTRAINT fk_employee_unit_unit
        FOREIGN KEY (unit_id) REFERENCES unit (id)
);

-- A supervisor may lead at most one unit. This can however change in the future,
-- so this separate table is used to represent this relationship. The supervisor_id is the PK
-- to enforce the one-to-one relationship.
CREATE TABLE supervisor_unit (
    supervisor_id BIGINT NOT NULL PRIMARY KEY,
    unit_id BIGINT NOT NULL,
    CONSTRAINT fk_supervisor_unit_supervisor
        FOREIGN KEY (supervisor_id) REFERENCES app_user (id),
    CONSTRAINT fk_supervisor_unit_unit
        FOREIGN KEY (unit_id) REFERENCES unit (id)
);

CREATE TABLE competency (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type competency_type NOT NULL,
    validity_months INTEGER NULL
);

CREATE TABLE qualification (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- Maps which competencies are required for a qualification.
CREATE TABLE qualification_requirement (
    qualification_id BIGINT NOT NULL,
    competency_id BIGINT NOT NULL,
    CONSTRAINT pk_qualification_requirement PRIMARY KEY (qualification_id, competency_id),
    CONSTRAINT fk_qualification_requirement_qualification
        FOREIGN KEY (qualification_id) REFERENCES qualification (id),
    CONSTRAINT fk_qualification_requirement_competency
        FOREIGN KEY (competency_id) REFERENCES competency (id)
);

-- Tracks which competencies an employee has, when they were issued, and when they expire.
CREATE TABLE employee_competency (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    competency_id BIGINT NOT NULL,
    issue_date DATE NOT NULL,
    -- Expiration date is calculated based on the issue date and the validity of the competency.
    -- If competency_validity_months is NULL, the expiration date is also NULL.
    expiration_date DATE NULL,
    CONSTRAINT fk_employee_competency_user
        FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_employee_competency_competency
        FOREIGN KEY (competency_id) REFERENCES competency (id),
    CONSTRAINT uq_employee_competency_user_competency UNIQUE (user_id, competency_id),
    CONSTRAINT chk_employee_competency_expiration
        CHECK (
            expiration_date IS NULL
            OR expiration_date >= issue_date
        )
);

CREATE TABLE renewal_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_credential_id BIGINT NOT NULL,
    renewal_date DATE NOT NULL,
    renewal_comment VARCHAR(500) NULL,
    CONSTRAINT uq_renewal_plan_employee_credential
        UNIQUE (employee_credential_id),
    CONSTRAINT fk_renewal_plan_employee_competency
        FOREIGN KEY (employee_credential_id) REFERENCES employee_competency (id)
);

CREATE TABLE employee_qualification (
    user_id BIGINT NOT NULL,
    qualification_id BIGINT NOT NULL,
    favourite BOOLEAN NOT NULL DEFAULT FALSE,
    critical BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_employee_qualification PRIMARY KEY (user_id, qualification_id),
    CONSTRAINT fk_employee_qualification_user
        FOREIGN KEY (user_id) REFERENCES app_user (id),
    CONSTRAINT fk_employee_qualification_qualification
        FOREIGN KEY (qualification_id) REFERENCES qualification (id)
);

