# This file will be used when running the whole application with docker compose.

spring.application.name=backend

# Needed to connect to the Database.
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# This means hibernate will only validate the DB schema based on the created entities (e.g. User.java),
# but will not create or update DB schema. Resources/db/migration folder is used for DB schema creation and updates.
spring.jpa.hibernate.ddl-auto=validate

# The locations of the migration script and the test data seeding script.
spring.flyway.locations=classpath:db/migration,classpath:db/seed

spring.jpa.open-in-view=false
